# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ac766b35e2e134d883d0904056dd1bfbbbce79e73f50ba4e01829876765ea8ca9c286e696367ada050fb2b952c387ad6a283af9ab1dfae6ec9c60ee9880ac62

test:
  secret_key_base: 52a9568939ca9f62d4a18d0f1849aba050148638ac3e6422ac46033d47b68974a3c8de952b0e190b84089e75931411079fa73335ecff38be0704135092b64030

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
